language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction --prefer-source --no-suggest"

matrix:
  include:
    - php: 7.2
      env:
        - COLLECT_COVERAGE=true
        - VALIDATE_CODING_STYLE=true
        - RUN_PHPSTAN=true
        - IGNORE_PLATFORMS=false
    - php: 7.3
      env:
        - COLLECT_COVERAGE=true
        - VALIDATE_CODING_STYLE=true
        - RUN_PHPSTAN=true
        - IGNORE_PLATFORMS=false
    - php: 7.4
      env:
        - COLLECT_COVERAGE=true
        - VALIDATE_CODING_STYLE=true
        - RUN_PHPSTAN=true
        - IGNORE_PLATFORMS=false
    - php: nightly
      env:
        - COLLECT_COVERAGE=false
        - IGNORE_PLATFORMS=true
        - RUN_PHPSTAN=false
        - VALIDATE_CODING_STYLE=false
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - travis_retry composer self-update

install:
  - if [ "$IGNORE_PLATFORMS" == "true" ]; then travis_retry composer update $COMPOSER_ARGS --ignore-platform-reqs; fi
  - if [ "$IGNORE_PLATFORMS" == "false" ]; then travis_retry composer update $COMPOSER_ARGS; fi

script:
  - if [ "$RUN_PHPSTAN" == "true" ]; then composer phpstan; fi
  - if [ "$VALIDATE_CODING_STYLE" == "true" ]; then composer phpcs; fi
  - composer phpunit

after_script:
  - if [ "$COLLECT_COVERAGE" == "true" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/clover.xml; fi
